color: null
fieldLayouts:
  6b4c1a62-f55c-4bc3-9604-9bfb89fa0214:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b60a5b3d-e4f4-42b5-a3d3-05854cca87ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2e43f27-9cc6-4cf7-a708-292c0803af09 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebd55090-f658-4814-bc28-19c72f00c699
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c757b7f-4691-4671-ad91-f823dbe9158d
        userCondition: null
handle: btnscontent
hasTitleField: true
icon: ''
name: BtnsContent
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
