color: null
fieldLayouts:
  9110fcb1-32b2-4fe7-94a7-8afc73ce1d91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fcb8c426-8f80-422c-92e2-1a5cad3acf4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11a24958-75d5-486f-a594-b3ba2da59f49
        userCondition: null
handle: contact
hasTitleField: true
icon: ''
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
