color: null
fieldLayouts:
  cc878379-460d-40d2-a442-1aa5ef83e77c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 39296330-04e2-4821-84cc-05164290a09d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cae79589-7081-4480-aec6-7e3deffc164a # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30c50cdb-6e6a-4359-9a9d-e1ab8ea1615b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cc5c3aa1-c9e5-4d5d-8abc-fd25b914aa53 # HeroImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2413a2b5-a943-4ad1-85fb-73af9ddeefbe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a07f91f-f205-4974-96d3-0c8cf3eebb4d
        userCondition: null
handle: herocontent
hasTitleField: true
icon: ''
name: HeroContent
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
