color: teal
fieldLayouts:
  c8cbe30b-d430-4f78-acbc-db9f9c26c5eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2abb0b3f-f4bb-4eea-aabe-5c3ce0735c71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ce66c85-f1e0-4f92-86be-654858c316f9 # RegularHero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47e211b4-4ecb-455b-a242-24728a1a0965
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b53bc985-b76d-4d20-9e71-fb00fb9b0f0c # HeroRegularBtns
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d06f0b26-3b2a-472b-be4e-bc0883b17147
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7df9081a-cb8a-46da-a900-63ea66482bd9 # TopicCards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90aafee5-fb70-455e-a209-d03330390fed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4f41399-0d84-47d8-a1cf-844257d168ee # UpdateTitles
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f474a2f-7fbb-40bc-8b1a-94038bf7b6a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3fe4bad-f58e-4e91-9866-321b3132cd16 # UpdateCards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 197b0d76-c0fa-47b4-9499-c90f32399fa4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c52fdcf-e690-45b4-b3e9-c9ad699deb6f # HomeCTAgrey
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf84c78a-9ace-48b1-8060-cbec871d522f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f41de67e-dc62-4f52-a266-e0e96611f294
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
