color: null
fieldLayouts:
  eb3d52d6-c69c-49de-8793-5e9b3eac29c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d2e43f27-9cc6-4cf7-a708-292c0803af09 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdac9d92-1914-4406-a76f-813e52b7bcbd
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 699a2975-46e2-427f-b53b-2b1799e0406c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9268092d-609f-4904-b455-1a735e39d361
        userCondition: null
handle: image
hasTitleField: true
icon: ''
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
