color: null
fieldLayouts:
  3fb933b8-74d5-4a87-8897-dee75672c730:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 161352a1-032a-4686-aad8-04246a976353
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 138121f2-e6f5-4e2e-91a0-04a1e7837cfc # TeamImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dfde371-a25a-4bdd-801e-cb17b21a0d60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfb1ee03-a85f-4fd2-8180-7067243b8f8c # Teamintro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e9bab21-93de-400b-8e15-bb5d2c14d5fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e324e03f-173c-48b5-9256-a811bb52d9b3 # TeamName
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca195b04-83c9-4760-a5c0-ef5b7460cdda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aca62386-0b9f-440a-84fa-45f843407eaa # TeamText
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64ba171c-a15a-49e4-9a8a-ffcaed9ce650
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d147ac2-f809-4f16-9e2a-afbf7b9ae562 # TeamIcon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bab8dac3-be09-44c1-afd0-4a5e26e2d77c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3436eca9-8eaa-4880-a216-3848ee519bd2
        userCondition: null
handle: teamcontent
hasTitleField: true
icon: ''
name: TeamContent
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
