color: null
fieldLayouts:
  c73a2b80-8d6d-4733-b1a0-004c3710f34d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 856ce903-3ec8-4819-9a4a-8eb28c1629f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3f09b19-41e4-44c2-8814-782a31435622 # text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e7f27c0-68ae-409f-ac4b-40648ed98570
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: da1d52b9-6bb1-49e7-8fff-2df011b2672c
        userCondition: null
handle: textblockupcontent
hasTitleField: true
icon: ''
name: TextBlockUPContent
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
