columnSuffix: null
handle: ctablue
instructions: null
name: CTAblue
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - c9ed8f00-54e0-42da-8b5f-85af1a051d0a # Text
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
