currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: image
layout: e5e23af0-6c62-45bf-bad7-433ef3cfab1f # Default
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: 1
prevParent: null
prevUrl: assets
sortOrder: 15
type: craft
url: assets
