currLabel: SEO
customIcon: null
enabled: true
handle: seo
icon: /var/www/html/vendor/ether/seo/src/icon-mask.svg
layout: e5e23af0-6c62-45bf-bad7-433ef3cfab1f # Default
level: 1
newWindow: false
parent: null
prevLabel: SEO
prevLevel: 1
prevParent: null
prevUrl: seo
sortOrder: 3
type: plugin
url: seo
