currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: e5e23af0-6c62-45bf-bad7-433ef3cfab1f # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 10
type: craft
url: settings
