currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: 8fe4ecc2-abed-47a7-927a-f41f14458530
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 10
type: craft
url: settings
