defaultPlacement: end
enableVersioning: true
entryTypes:
  - d5091483-e587-49e2-91b8-76d59c4f4de3 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4b05b207-5903-4ce1-9112-542d6c4b2bcf: # Vlaskracht
    enabledByDefault: true
    hasUrls: true
    template: about/index.twig
    uriFormat: about
type: single
