defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7131cbbc-052f-443d-ad8b-2b6b19e21374 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4b05b207-5903-4ce1-9112-542d6c4b2bcf: # Vlaskracht
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
