defaultPlacement: end
enableVersioning: true
entryTypes:
  - 46e6d115-f1af-4509-af06-5efbe5af8f19 # Projects
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4b05b207-5903-4ce1-9112-542d6c4b2bcf: # Vlaskracht
    enabledByDefault: true
    hasUrls: true
    template: projects/index.twig
    uriFormat: projects
type: single
